package Armado;
import Armado.ArmarMapa;
import inicio.Confi;
import inicio.SeleccionarMapa;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class ArmarContinentes extends javax.swing.JFrame {
 int poaX, poaY;
 int piezasColocadasCorrectamente = 0;
 
   private boolean sonidoActivo = true; // Variable de control para el sonido
      Confi confi = new Confi();
 
    public ArmarContinentes() {
           initComponents();
        setLocationRelativeTo(null);
        setResizable(Boolean.FALSE);

        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Espacio1 = new javax.swing.JLabel();
        Espacio2 = new javax.swing.JLabel();
        Espacio3 = new javax.swing.JLabel();
        Espacio5 = new javax.swing.JLabel();
        Espacio4 = new javax.swing.JLabel();
        Espacio6 = new javax.swing.JLabel();
        btanterior = new javax.swing.JButton();
        asia = new javax.swing.JLabel();
        africa = new javax.swing.JLabel();
        america = new javax.swing.JLabel();
        antartida = new javax.swing.JLabel();
        oceania = new javax.swing.JLabel();
        europa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonContinuar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 239, 234));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 800));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Espacio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Armado/Bundle"); // NOI18N
        Espacio1.setText(bundle.getString("ArmarMapaContinentes.Espacio1.text")); // NOI18N
        jPanel1.add(Espacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 357, 40, 20));

        Espacio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14.png"))); // NOI18N
        Espacio2.setText(bundle.getString("ArmarMapaContinentes.Espacio2.text")); // NOI18N
        jPanel1.add(Espacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 490, -1, 20));

        Espacio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14.png"))); // NOI18N
        Espacio3.setText(bundle.getString("ArmarMapaContinentes.Espacio3.text")); // NOI18N
        jPanel1.add(Espacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 327, 20, 20));

        Espacio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14.png"))); // NOI18N
        Espacio5.setText(bundle.getString("ArmarMapaContinentes.Espacio5.text")); // NOI18N
        jPanel1.add(Espacio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 575, 20, 30));

        Espacio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14.png"))); // NOI18N
        Espacio4.setText(bundle.getString("ArmarMapaContinentes.Espacio4.text")); // NOI18N
        jPanel1.add(Espacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 388, 20, 20));

        Espacio6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14.png"))); // NOI18N
        Espacio6.setText(bundle.getString("ArmarMapaContinentes.Espacio6.text")); // NOI18N
        jPanel1.add(Espacio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 20, 20));

        btanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btanterior.setText(bundle.getString("ArmarMapaContinentes.btanterior.text")); // NOI18N
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 740, 140, 50));

        asia.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asia.png"))); // NOI18N
        asia.setText(bundle.getString("ArmarMapaContinentes.asia.text")); // NOI18N
        asia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                asiaMouseDragged(evt);
            }
        });
        asia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asiaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                asiaMouseReleased(evt);
            }
        });
        jPanel1.add(asia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, -1, -1));

        africa.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        africa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/africa.png"))); // NOI18N
        africa.setText(bundle.getString("ArmarMapaContinentes.africa.text")); // NOI18N
        africa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                africaMouseDragged(evt);
            }
        });
        africa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                africaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                africaMouseReleased(evt);
            }
        });
        jPanel1.add(africa, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, -1, -1));

        america.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        america.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/america.png"))); // NOI18N
        america.setText(bundle.getString("ArmarMapaContinentes.america.text")); // NOI18N
        america.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                americaMouseDragged(evt);
            }
        });
        america.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                americaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                americaMouseReleased(evt);
            }
        });
        jPanel1.add(america, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, 320, 440));

        antartida.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        antartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/antarctica.png"))); // NOI18N
        antartida.setText(bundle.getString("ArmarMapaContinentes.antartida.text")); // NOI18N
        antartida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                antartidaMouseDragged(evt);
            }
        });
        antartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                antartidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                antartidaMouseReleased(evt);
            }
        });
        jPanel1.add(antartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, -1, -1));

        oceania.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        oceania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/oceania.png"))); // NOI18N
        oceania.setText(bundle.getString("ArmarMapaContinentes.oceania.text")); // NOI18N
        oceania.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                oceaniaMouseDragged(evt);
            }
        });
        oceania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oceaniaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oceaniaMouseReleased(evt);
            }
        });
        jPanel1.add(oceania, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, -1, -1));

        europa.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        europa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/europa.png"))); // NOI18N
        europa.setText(bundle.getString("ArmarMapaContinentes.europa.text")); // NOI18N
        europa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                europaMouseDragged(evt);
            }
        });
        europa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                europaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                europaMouseReleased(evt);
            }
        });
        jPanel1.add(europa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 160, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 202, 84), 10));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 700, 450));

        BotonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comprobar.png"))); // NOI18N
        BotonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 150, 50));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 62)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 107, 31));
        jLabel4.setText("Continetes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 340, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Barra.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 480, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Diseño sin título.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void africaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_africaMouseDragged
 int deltaX = evt.getX() - poaX;
          int deltaY = evt.getY() - poaY;
          
          int newLabelX = africa.getX() + deltaX;
          int newLabelY = africa.getY() + deltaY;
          africa.setLocation(newLabelX, newLabelY);
    }//GEN-LAST:event_africaMouseDragged

    private void americaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_americaMouseDragged
     int deltaX = evt.getX() - poaX;
          int deltaY = evt.getY() - poaY;
          
          int newLabelX = america.getX() + deltaX;
          int newLabelY = america.getY() + deltaY;
          america.setLocation(newLabelX, newLabelY);
    }//GEN-LAST:event_americaMouseDragged

    private void europaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_europaMouseDragged
       int deltaX = evt.getX() - poaX;
          int deltaY = evt.getY() - poaY;
          
          int newLabelX = europa.getX() + deltaX;
          int newLabelY = europa.getY() + deltaY;
          europa.setLocation(newLabelX, newLabelY);
    }//GEN-LAST:event_europaMouseDragged

    private void asiaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asiaMouseDragged
        int deltaX = evt.getX() - poaX;
          int deltaY = evt.getY() - poaY;
          
          int newLabelX = asia.getX() + deltaX;
          int newLabelY = asia.getY() + deltaY;
          asia.setLocation(newLabelX, newLabelY);
    }//GEN-LAST:event_asiaMouseDragged

    private void oceaniaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oceaniaMouseDragged
       int deltaX = evt.getX() - poaX;
          int deltaY = evt.getY() - poaY;
          
          int newLabelX = oceania.getX() + deltaX;
          int newLabelY = oceania.getY() + deltaY;
          oceania.setLocation(newLabelX, newLabelY);
    }//GEN-LAST:event_oceaniaMouseDragged

    private void antartidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antartidaMouseDragged
       int deltaX = evt.getX() - poaX;
          int deltaY = evt.getY() - poaY;
          
          int newLabelX = antartida.getX() + deltaX;
          int newLabelY = antartida.getY() + deltaY;
          antartida.setLocation(newLabelX, newLabelY);
    }//GEN-LAST:event_antartidaMouseDragged

    private void americaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_americaMousePressed
         poaX = evt.getX();
          poaY=evt.getY();
          String rutaSonido = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\geography\\wav\\transformaciones\\continetesAudios\\america.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido

    }//GEN-LAST:event_americaMousePressed

    private void africaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_africaMousePressed
        poaX = evt.getX();
          poaY=evt.getY();
String rutaSonido = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\geography\\wav\\transformaciones\\continetesAudios\\africa.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido
    }//GEN-LAST:event_africaMousePressed

    private void europaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_europaMousePressed
         poaX = evt.getX();
          poaY=evt.getY();
String rutaSonido = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\geography\\wav\\transformaciones\\continetesAudios\\europa.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido
    }//GEN-LAST:event_europaMousePressed

    private void asiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asiaMousePressed
      poaX = evt.getX();
          poaY=evt.getY();
String rutaSonido = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\geography\\wav\\transformaciones\\continetesAudios\\asia.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido
    }//GEN-LAST:event_asiaMousePressed

    private void oceaniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oceaniaMousePressed
        poaX = evt.getX();
          poaY=evt.getY();
String rutaSonido = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\geography\\wav\\transformaciones\\continetesAudios\\oceania.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido
    }//GEN-LAST:event_oceaniaMousePressed

    private void antartidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antartidaMousePressed
       poaX = evt.getX();
          poaY=evt.getY();
String rutaSonido = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\geography\\wav\\transformaciones\\continetesAudios\\antartida.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido
    }//GEN-LAST:event_antartidaMousePressed

    private void americaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_americaMouseReleased
verificarTodasLasPiezas();
        if (evt.getComponent().getBounds().intersects(Espacio1.getBounds())) {
        String rutaIcono = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono1 = new ImageIcon(rutaIcono);
        if(icono1.getDescription().equals(rutaIcono)){
            int x = Espacio1.getX()+ (Espacio1.getWidth() / 2) - (america.getWidth() / 2);
            int y = Espacio1.getY()+ (Espacio1.getWidth() / 2) - (america.getWidth() / 2);
            america.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio2.getBounds())) {
        String rutaIcono2 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono2 = new ImageIcon(rutaIcono2);
        if(icono2.getDescription().equals(rutaIcono2)){
            int x = Espacio2.getX()+ (Espacio2.getWidth() / 2) - (america.getWidth() / 2);
            int y = Espacio2.getY()+ (Espacio2.getWidth() / 2) - (america.getWidth() / 2);
            america.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio3.getBounds())) {
        String rutaIcono3 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono3 = new ImageIcon(rutaIcono3);
        if(icono3.getDescription().equals(rutaIcono3)){
            int x = Espacio3.getX()+ (Espacio3.getWidth() / 2) - (america.getWidth() / 2);
            int y = Espacio3.getY()+ (Espacio3.getWidth() / 2) - (america.getWidth() / 2);
            america.setLocation(x, y);
        } 
    } else if(evt.getComponent().getBounds().intersects(Espacio4.getBounds())) {
        String rutaIcono4 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono4 = new ImageIcon(rutaIcono4);
        if(icono4.getDescription().equals(rutaIcono4)){
            int x = Espacio4.getX()+ (Espacio4.getWidth() / 2) - (america.getWidth() / 2);
            int y = Espacio4.getY()+ (Espacio4.getWidth() / 2) - (america.getWidth() / 2);
            america.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio5.getBounds())) {
        String rutaIcono5 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono5 = new ImageIcon(rutaIcono5);
        if(icono5.getDescription().equals(rutaIcono5)){
            int x = Espacio5.getX()+ (Espacio5.getWidth() / 2) - (america.getWidth() / 2);
            int y = Espacio5.getY()+ (Espacio5.getWidth() / 2) - (america.getWidth() / 2);
            america.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio6.getBounds())) {
        String rutaIcono6 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono6 = new ImageIcon(rutaIcono6);
        if(icono6.getDescription().equals(rutaIcono6)){
            int x = Espacio6.getX()+ (Espacio6.getWidth() / 2) - (america.getWidth() / 2);
            int y = Espacio6.getY()+ (Espacio6.getWidth() / 2) - (america.getWidth() / 2);
            america.setLocation(x, y);
         }
         
    }     }//GEN-LAST:event_americaMouseReleased

    private void africaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_africaMouseReleased
 
        verificarTodasLasPiezas();
        if (evt.getComponent().getBounds().intersects(Espacio1.getBounds())) {
        String rutaIcono = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono1 = new ImageIcon(rutaIcono);
        if(icono1.getDescription().equals(rutaIcono)){
            int x = Espacio1.getX()+ (Espacio1.getWidth() / 2) - (africa.getWidth() / 2);
            int y = Espacio1.getY()+ (Espacio1.getWidth() / 2) - (africa.getWidth() / 2);
            africa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio2.getBounds())) {
        String rutaIcono2 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono2 = new ImageIcon(rutaIcono2);
        if(icono2.getDescription().equals(rutaIcono2)){
            int x = Espacio2.getX()+ (Espacio2.getWidth() / 2) - (africa.getWidth() / 2);
            int y = Espacio2.getY()+ (Espacio2.getWidth() / 2) - (africa.getWidth() / 2);
            africa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio3.getBounds())) {
        String rutaIcono3 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono3 = new ImageIcon(rutaIcono3);
        if(icono3.getDescription().equals(rutaIcono3)){
            int x = Espacio3.getX()+ (Espacio3.getWidth() / 2) - (africa.getWidth() / 2);
            int y = Espacio3.getY()+ (Espacio3.getWidth() / 2) - (africa.getWidth() / 2);
            africa.setLocation(x, y);
        } 
    } else if(evt.getComponent().getBounds().intersects(Espacio4.getBounds())) {
        String rutaIcono4 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono4 = new ImageIcon(rutaIcono4);
        if(icono4.getDescription().equals(rutaIcono4)){
            int x = Espacio4.getX()+ (Espacio4.getWidth() / 2) - (africa.getWidth() / 2);
            int y = Espacio4.getY()+ (Espacio4.getWidth() / 2) - (africa.getWidth() / 2);
            africa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio5.getBounds())) {
        String rutaIcono5 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono5 = new ImageIcon(rutaIcono5);
        if(icono5.getDescription().equals(rutaIcono5)){
            int x = Espacio5.getX()+ (Espacio5.getWidth() / 2) - (africa.getWidth() / 2);
            int y = Espacio5.getY()+ (Espacio5.getWidth() / 2) - (africa.getWidth() / 2);
            africa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio6.getBounds())) {
        String rutaIcono6 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono6 = new ImageIcon(rutaIcono6);
        if(icono6.getDescription().equals(rutaIcono6)){
            int x = Espacio6.getX()+ (Espacio6.getWidth() / 2) - (africa.getWidth() / 2);
            int y = Espacio6.getY()+ (Espacio6.getWidth() / 2) - (africa.getWidth() / 2);
            africa.setLocation(x, y);
         }
    
    }      }//GEN-LAST:event_africaMouseReleased

    private void europaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_europaMouseReleased
        verificarTodasLasPiezas(); 
        
        if (evt.getComponent().getBounds().intersects(Espacio1.getBounds())) {
        String rutaIcono = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono1 = new ImageIcon(rutaIcono);
        if(icono1.getDescription().equals(rutaIcono)){
            int x = Espacio1.getX()+ (Espacio1.getWidth() / 2) - (europa.getWidth() / 2);
            int y = Espacio1.getY()+ (Espacio1.getWidth() / 2) - (europa.getWidth() / 2);
            europa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio2.getBounds())) {
        String rutaIcono2 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono2 = new ImageIcon(rutaIcono2);
        if(icono2.getDescription().equals(rutaIcono2)){
            int x = Espacio2.getX()+ (Espacio2.getWidth() / 2) - (europa.getWidth() / 2);
            int y = Espacio2.getY()+ (Espacio2.getWidth() / 2) - (europa.getWidth() / 2);
            europa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio3.getBounds())) {
        String rutaIcono3 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono3 = new ImageIcon(rutaIcono3);
        if(icono3.getDescription().equals(rutaIcono3)){
            int x = Espacio3.getX()+ (Espacio3.getWidth() / 2) - (europa.getWidth() / 2);
            int y = Espacio3.getY()+ (Espacio3.getWidth() / 2) - (europa.getWidth() / 2);
            europa.setLocation(x, y);
        } 
    } else if(evt.getComponent().getBounds().intersects(Espacio4.getBounds())) {
        String rutaIcono4 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono4 = new ImageIcon(rutaIcono4);
        if(icono4.getDescription().equals(rutaIcono4)){
            int x = Espacio4.getX()+ (Espacio4.getWidth() / 2) - (europa.getWidth() / 2);
            int y = Espacio4.getY()+ (Espacio4.getWidth() / 2) - (europa.getWidth() / 2);
            europa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio5.getBounds())) {
        String rutaIcono5 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono5 = new ImageIcon(rutaIcono5);
        if(icono5.getDescription().equals(rutaIcono5)){
            int x = Espacio5.getX()+ (Espacio5.getWidth() / 2) - (europa.getWidth() / 2);
            int y = Espacio5.getY()+ (Espacio5.getWidth() / 2) - (europa.getWidth() / 2);
            europa.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio6.getBounds())) {
        String rutaIcono6 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono6 = new ImageIcon(rutaIcono6);
        if(icono6.getDescription().equals(rutaIcono6)){
            int x = Espacio6.getX()+ (Espacio6.getWidth() / 2) - (europa.getWidth() / 2);
            int y = Espacio6.getY()+ (Espacio6.getWidth() / 2) - (europa.getWidth() / 2);
            europa.setLocation(x, y);
         }
    }     
    }//GEN-LAST:event_europaMouseReleased

    private void asiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asiaMouseReleased
          
        verificarTodasLasPiezas();
        
        if (evt.getComponent().getBounds().intersects(Espacio1.getBounds())) {
        String rutaIcono = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono1 = new ImageIcon(rutaIcono);
        if(icono1.getDescription().equals(rutaIcono)){
            int x = Espacio1.getX()+ (Espacio1.getWidth() / 2) - (asia.getWidth() / 2);
            int y = Espacio1.getY()+ (Espacio1.getWidth() / 2) - (asia.getWidth() / 2);
            asia.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio2.getBounds())) {
        String rutaIcono2 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono2 = new ImageIcon(rutaIcono2);
        if(icono2.getDescription().equals(rutaIcono2)){
            int x = Espacio2.getX()+ (Espacio2.getWidth() / 2) - (asia.getWidth() / 2);
            int y = Espacio2.getY()+ (Espacio2.getWidth() / 2) - (asia.getWidth() / 2);
            asia.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio3.getBounds())) {
        String rutaIcono3 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono3 = new ImageIcon(rutaIcono3);
        if(icono3.getDescription().equals(rutaIcono3)){
            int x = Espacio3.getX()+ (Espacio3.getWidth() / 2) - (asia.getWidth() / 2);
            int y = Espacio3.getY()+ (Espacio3.getWidth() / 2) - (asia.getWidth() / 2);
            asia.setLocation(x, y);
        } 
    } else if(evt.getComponent().getBounds().intersects(Espacio4.getBounds())) {
        String rutaIcono4 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono4 = new ImageIcon(rutaIcono4);
        if(icono4.getDescription().equals(rutaIcono4)){
            int x = Espacio4.getX()+ (Espacio4.getWidth() / 2) - (asia.getWidth() / 2);
            int y = Espacio4.getY()+ (Espacio4.getWidth() / 2) - (asia.getWidth() / 2);
            asia.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio5.getBounds())) {
        String rutaIcono5 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono5 = new ImageIcon(rutaIcono5);
        if(icono5.getDescription().equals(rutaIcono5)){
            int x = Espacio5.getX()+ (Espacio5.getWidth() / 2) - (asia.getWidth() / 2);
            int y = Espacio5.getY()+ (Espacio5.getWidth() / 2) - (asia.getWidth() / 2);
            asia.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio6.getBounds())) {
        String rutaIcono6 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono6 = new ImageIcon(rutaIcono6);
        if(icono6.getDescription().equals(rutaIcono6)){
            int x = Espacio6.getX()+ (Espacio6.getWidth() / 2) - (asia.getWidth() / 2);
            int y = Espacio6.getY()+ (Espacio6.getWidth() / 2) - (asia.getWidth() / 2);
            asia.setLocation(x, y);
         }
    }     
    }//GEN-LAST:event_asiaMouseReleased

    private void oceaniaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oceaniaMouseReleased
        verificarTodasLasPiezas(); 
        
        if (evt.getComponent().getBounds().intersects(Espacio1.getBounds())) {
        String rutaIcono = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono1 = new ImageIcon(rutaIcono);
        if(icono1.getDescription().equals(rutaIcono)){
            int x = Espacio1.getX()+ (Espacio1.getWidth() / 2) - (oceania.getWidth() / 2);
            int y = Espacio1.getY()+ (Espacio1.getWidth() / 2) - (oceania.getWidth() / 2);
            oceania.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio2.getBounds())) {
        String rutaIcono2 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono2 = new ImageIcon(rutaIcono2);
        if(icono2.getDescription().equals(rutaIcono2)){
            int x = Espacio2.getX()+ (Espacio2.getWidth() / 2) - (oceania.getWidth() / 2);
            int y = Espacio2.getY()+ (Espacio2.getWidth() / 2) - (oceania.getWidth() / 2);
            oceania.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio3.getBounds())) {
        String rutaIcono3 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono3 = new ImageIcon(rutaIcono3);
        if(icono3.getDescription().equals(rutaIcono3)){
            int x = Espacio3.getX()+ (Espacio3.getWidth() / 2) - (oceania.getWidth() / 2);
            int y = Espacio3.getY()+ (Espacio3.getWidth() / 2) - (oceania.getWidth() / 2);
            oceania.setLocation(x, y);
        } 
    } else if(evt.getComponent().getBounds().intersects(Espacio4.getBounds())) {
        String rutaIcono4 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono4 = new ImageIcon(rutaIcono4);
        if(icono4.getDescription().equals(rutaIcono4)){
            int x = Espacio4.getX()+ (Espacio4.getWidth() / 2) - (oceania.getWidth() / 2);
            int y = Espacio4.getY()+ (Espacio4.getWidth() / 2) - (oceania.getWidth() / 2);
            oceania.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio5.getBounds())) {
        String rutaIcono5 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono5 = new ImageIcon(rutaIcono5);
        if(icono5.getDescription().equals(rutaIcono5)){
            int x = Espacio5.getX()+ (Espacio5.getWidth() / 2) - (oceania.getWidth() / 2);
            int y = Espacio5.getY()+ (Espacio5.getWidth() / 2) - (oceania.getWidth() / 2);
            oceania.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio6.getBounds())) {
        String rutaIcono6 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono6 = new ImageIcon(rutaIcono6);
        if(icono6.getDescription().equals(rutaIcono6)){
            int x = Espacio6.getX()+ (Espacio6.getWidth() / 2) - (oceania.getWidth() / 2);
            int y = Espacio6.getY()+ (Espacio6.getWidth() / 2) - (oceania.getWidth() / 2);
            oceania.setLocation(x, y);
         }
    }     
    }//GEN-LAST:event_oceaniaMouseReleased

    private void antartidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antartidaMouseReleased
        verificarTodasLasPiezas();
        
        if (evt.getComponent().getBounds().intersects(Espacio1.getBounds())) {
        String rutaIcono = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono1 = new ImageIcon(rutaIcono);
        if(icono1.getDescription().equals(rutaIcono)){
            int x = Espacio1.getX()+ (Espacio1.getWidth() / 2) - (antartida.getWidth() / 2);
            int y = Espacio1.getY()+ (Espacio1.getWidth() / 2) - (antartida.getWidth() / 2);
            antartida.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio2.getBounds())) {
        String rutaIcono2 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono2 = new ImageIcon(rutaIcono2);
        if(icono2.getDescription().equals(rutaIcono2)){
            int x = Espacio2.getX()+ (Espacio2.getWidth() / 2) - (antartida.getWidth() / 2);
            int y = Espacio2.getY()+ (Espacio2.getWidth() / 2) - (antartida.getWidth() / 2);
            antartida.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio3.getBounds())) {
        String rutaIcono3 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono3 = new ImageIcon(rutaIcono3);
        if(icono3.getDescription().equals(rutaIcono3)){
            int x = Espacio3.getX()+ (Espacio3.getWidth() / 2) - (antartida.getWidth() / 2);
            int y = Espacio3.getY()+ (Espacio3.getWidth() / 2) - (antartida.getWidth() / 2);
            antartida.setLocation(x, y);
        } 
    } else if(evt.getComponent().getBounds().intersects(Espacio4.getBounds())) {
        String rutaIcono4 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono4 = new ImageIcon(rutaIcono4);
        if(icono4.getDescription().equals(rutaIcono4)){
            int x = Espacio4.getX()+ (Espacio4.getWidth() / 2) - (antartida.getWidth() / 2);
            int y = Espacio4.getY()+ (Espacio4.getWidth() / 2) - (antartida.getWidth() / 2);
            antartida.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio5.getBounds())) {
        String rutaIcono5 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono5 = new ImageIcon(rutaIcono5);
        if(icono5.getDescription().equals(rutaIcono5)){
            int x = Espacio5.getX()+ (Espacio5.getWidth() / 2) - (antartida.getWidth() / 2);
            int y = Espacio5.getY()+ (Espacio5.getWidth() / 2) - (antartida.getWidth() / 2);
            antartida.setLocation(x, y);
        }
    } else if(evt.getComponent().getBounds().intersects(Espacio6.getBounds())) {
        String rutaIcono6 = "C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\nombre.png";
        ImageIcon icono6 = new ImageIcon(rutaIcono6);
        if(icono6.getDescription().equals(rutaIcono6)){
            int x = Espacio6.getX();
            int y = Espacio6.getY();
            antartida.setLocation(x, y);
         }
    }    
    }//GEN-LAST:event_antartidaMouseReleased
//
    
      public void reproducirSonido(String rutaArchivo) {
    if (!Confi.isSonidoActivado()) return; // Accede de manera estática a la variable

    try {
        AudioInputStream audioInput = AudioSystem.getAudioInputStream(new File(rutaArchivo));
        Clip clip = AudioSystem.getClip();
        clip.open(audioInput);
        clip.start(); // Reproducir el sonido
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    
    
    
    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseReleased

    private void BotonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonContinuarActionPerformed
   verificarTodasLasPiezas();

    // Verificar si las piezas colocadas correctamente son menos de 23
    if (piezasColocadasCorrectamente < 6) {
        JOptionPane.showMessageDialog(this, "Aún no se han colocado todas las piezas correctamente.");
    }
    
    }//GEN-LAST:event_BotonContinuarActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed
        SeleccionarMapa secm = new SeleccionarMapa();
        secm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btanteriorActionPerformed

    
 private void verificarTodasLasPiezas() {
    // Resetear el contador de piezas colocadas correctamente
    piezasColocadasCorrectamente = 0;

    // Verificar si la pieza 1 está en su espacio correcto (Espacio1)
    if (america.getBounds().intersects(Espacio1.getBounds())) {
        piezasColocadasCorrectamente++;
    }

    // Verificar si la pieza 2 está en su espacio correcto (Espacio2)
    if (africa.getBounds().intersects(Espacio2.getBounds())) {
        piezasColocadasCorrectamente++;
    }

    // Verificar si la pieza 3 está en su espacio correcto (Espacio3)
    if (europa.getBounds().intersects(Espacio3.getBounds())) {
        piezasColocadasCorrectamente++;
    }

    // Verificar si la pieza 4 está en su espacio correcto (Espacio4)
    if (asia.getBounds().intersects(Espacio4.getBounds())) {
        piezasColocadasCorrectamente++;
    }

    // Verificar si la pieza 5 está en su espacio correcto (Espacio5)
    if (oceania.getBounds().intersects(Espacio5.getBounds())) {
        piezasColocadasCorrectamente++;
    }
    
    if (antartida.getBounds().intersects(Espacio6.getBounds())) {
        piezasColocadasCorrectamente++;
    }

    
    
    
    
    // Solo mostrar el mensaje cuando todas las piezas están colocadas correctamente
    if (piezasColocadasCorrectamente == 6) {
        //FELICITACIONES SONIDO
    
    String rutaSonido ="C:\\Users\\jhoel\\OneDrive\\Documentos\\NetBeansProjects\\RompecabezasGeografico\\src\\img\\felicidades.wav";
    reproducirSonido(rutaSonido); // Reproducir el sonido
    
    
        JOptionPane.showMessageDialog(this, "¡Todas las piezas están en su posición correcta!");
    }
}
   
    
    
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArmarContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArmarContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArmarContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArmarContinentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArmarContinentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonContinuar;
    private javax.swing.JLabel Espacio1;
    private javax.swing.JLabel Espacio2;
    private javax.swing.JLabel Espacio3;
    private javax.swing.JLabel Espacio4;
    private javax.swing.JLabel Espacio5;
    private javax.swing.JLabel Espacio6;
    private javax.swing.JLabel africa;
    private javax.swing.JLabel america;
    private javax.swing.JLabel antartida;
    private javax.swing.JLabel asia;
    private javax.swing.JButton btanterior;
    private javax.swing.JLabel europa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oceania;
    // End of variables declaration//GEN-END:variables
}
