/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicio;

import Armado.ArmarPaisesSudamerica;
import Armado.NorteAmerica;
import Armado.PaisesCentroCaribe;

/**
 *
 * @author jhoel
 */
public class PartesDeAmerica extends javax.swing.JFrame {

    /**
     * Creates new form PartesDeAmerica
     */
    public PartesDeAmerica() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(Boolean.FALSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SurAmerica = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CentroCaribe = new javax.swing.JButton();
        Norte = new javax.swing.JButton();
        btanterior = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("Seleccionar parte de America");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 670, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sudamerica");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        SurAmerica.setBackground(new java.awt.Color(241, 239, 234));
        SurAmerica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sud.png"))); // NOI18N
        SurAmerica.setText("jButton1");
        SurAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurAmericaActionPerformed(evt);
            }
        });
        jPanel1.add(SurAmerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, 370));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Norte America");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Centro America y el Caribe");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        CentroCaribe.setBackground(new java.awt.Color(241, 239, 234));
        CentroCaribe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CentroAmerica.png"))); // NOI18N
        CentroCaribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentroCaribeActionPerformed(evt);
            }
        });
        jPanel1.add(CentroCaribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 210, 370));

        Norte.setBackground(new java.awt.Color(241, 239, 234));
        Norte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/northamericaaaa (1).png"))); // NOI18N
        Norte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorteActionPerformed(evt);
            }
        });
        jPanel1.add(Norte, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 210, 370));

        btanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, 147, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio/fondo (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SurAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurAmericaActionPerformed
        ArmarPaisesSudamerica  secm = new ArmarPaisesSudamerica ();
        secm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_SurAmericaActionPerformed

    private void CentroCaribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentroCaribeActionPerformed
        PaisesCentroCaribe  secm = new PaisesCentroCaribe ();
        secm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CentroCaribeActionPerformed

    private void NorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorteActionPerformed
        NorteAmerica secm = new NorteAmerica();
    secm.setVisible(true);
    //secm.IniciarCronometro(); // Iniciar el cronómetro en el nuevo JFrame de inmediato
    this.dispose();
        
    }//GEN-LAST:event_NorteActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed
        SeleccionarMapa secm = new SeleccionarMapa ();
        secm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btanteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartesDeAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartesDeAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartesDeAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartesDeAmerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartesDeAmerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CentroCaribe;
    private javax.swing.JButton Norte;
    private javax.swing.JButton SurAmerica;
    private javax.swing.JButton btanterior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
