package inicio;


import Armado.ArmarMapaContinentes;
import Armado.ArmarMapa;
import Armado.ArmarContinentes;
import Armado.ArmarPaisesSudamerica;
import inicio.Inicio;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlumnosET20
 */
public class SeleccionarMapa extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarMapa
     */
    public SeleccionarMapa() {
        initComponents();
         setLocationRelativeTo(null);
        setResizable(Boolean.FALSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        btargentina = new javax.swing.JButton();
        btsudamerica = new javax.swing.JButton();
        btcontinentes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btanterior = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 239, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btargentina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/map1.png"))); // NOI18N
        btargentina.setBorderPainted(false);
        btargentina.setFocusPainted(false);
        btargentina.setFocusable(false);
        btargentina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btargentinaActionPerformed(evt);
            }
        });
        jPanel1.add(btargentina, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 220, 296));

        btsudamerica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/amen.png"))); // NOI18N
        btsudamerica.setBorder(null);
        btsudamerica.setFocusPainted(false);
        btsudamerica.setFocusable(false);
        btsudamerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsudamericaActionPerformed(evt);
            }
        });
        jPanel1.add(btsudamerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 214, 297));

        btcontinentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton continentes.png"))); // NOI18N
        btcontinentes.setBorderPainted(false);
        btcontinentes.setFocusPainted(false);
        btcontinentes.setFocusable(false);
        btcontinentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcontinentesActionPerformed(evt);
            }
        });
        jPanel1.add(btcontinentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 210, 300));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel3.setText("Seleccionar mapa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 493, 48));

        btanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 147, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btargentinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btargentinaActionPerformed
         ArmarMapa secm = new ArmarMapa ();
        secm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btargentinaActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed
        Inicio secm = new Inicio ();
        secm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btanteriorActionPerformed

    private void btsudamericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsudamericaActionPerformed
        PartesDeAmerica  secm = new PartesDeAmerica ();
        secm.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btsudamericaActionPerformed

    private void btcontinentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcontinentesActionPerformed
       ArmarContinentes secm = new ArmarContinentes ();
        secm.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btcontinentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarMapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btanterior;
    private javax.swing.JButton btargentina;
    private javax.swing.JButton btcontinentes;
    private javax.swing.JButton btsudamerica;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
